version: '3.8'
services:
  web:
    image: php:8.1-apache
    container_name: php-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./mySqlDB:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root

volumes:
  mysqlDB: {}